ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= API REST client

anchor:bookmark-b[]

== DEFINES
=== Timeout for REST requests
==== Function:
 Default timeout for REST requests when waiting for a response

==== Note:
[NOTE]
Fixed value. To change ELClientRest.h must be changed

==== Prototype:
[source, c]
#define DEFAULT_REST_TIMEOUT  5000

==== Parameters:
==== Defaults:
 5000ms

==== Return:
==== Example:

== FUNCTIONS
=== class ELClientRest
==== Function:
 The ELClientRest class makes simple REST requests to a remote server. Each instance is used to communicate with one server and multiple instances can be created to make requests to multiple servers.
 The ELClientRest class does not support concurrent requests to the same server because only a single response can be recevied at a time and the responses of the two requests may arrive out of order.

==== Note:
[NOTE]
A major limitation of the REST class is that it does not store the response body. The response status is saved in the class instance, so after a request completes and before the next request is made a call to getResponse will return the status. However, only a pointer to the response body is saved, which means that if any other message arrives and is processed then the response body is overwritten by it. What this means is that if you need the response body you best use waitResponse or ensure that any call to ELClient::process is followed by a call to getResponse. Ideally someone improves this class to take a callback into the user's sketch?

[NOTE]
Another limitation is that the response body is 100 chars long at most, this is due to the limitation of the SLIP protocol buffer available.

==== Prototype:
[source, c]
ELClientRest(ELClient *e);

==== Parameters:
 ELClient *e:: Pointer to ELClient. Check ELClient API documentation.

==== Defaults:

==== Return:

==== Example:
[source, c++]
ELClientRest tcp(&esp);

___
___
=== begin
==== Function:
 Initialize communication to a remote server, this communicates with esp-link but does not open a connection to the remote server. Host may be a hostname or an IP address, security causes HTTPS to be used (not yet supported). Returns 0 if the set-up is successful, returns a negative error code if it failed.

==== Note:
[WARNING]
Max 4 connections are supported!

[WARNING]
Secure connection is not supported!

==== Prototype:
[source, c]
int begin(const char* host, uint16_t port=80, boolean security=false);

==== Parameters:
 const char* host:: Host to be connected. Can be a URL or an IP address in the format of xxx.xxx.xxx.xxx .
 uint16_t port:: Port to be used to send/receive packets.
 boolean security:: Request secure connection to the REST server (NOT SUPPORTED)

==== Defaults:
 uint16_t port:: Defaults to 80 if not set in the function call
 boolean security:: Defaults to FALSE if not set in the function call

==== Return:
 int <result>:: 0 if successfull or negative error code

 Error codes:
 -1 Wrong number of arguments (should never happen)
 -2 hostname longer than 128 characters
 -3 out of memory (ESP8266)
 -4 invalid hostname
 -5 invalid port number
 -6 other internal error (ESP8266)

==== Example:
[source, c++]
int err = rest.begin("www.timeapi.org");
if (err != 0) {
  Serial.print("REST begin failed: ");
  Serial.println(err);
  while(1) ;
}

___
___
=== request
==== Function:
 Make a request to the remote server. The data must be null-terminated or the length must be specified.

==== Note:

==== Prototype:
[source, c]
 void request(const char* path, const char* method, const char* data=NULL);
 void request(const char* path, const char* method, const char* data, int len);

==== Parameters:
 const char* path:: Path that extends the URL of the REST request (command or data for the REST server)
 const char* method:: REST method, allowed values are "GET", "POST", "PUT" or "DELETE"
 const char* data:: Pointer to data buffer
 int len:: Size of data buffer

==== Defaults:
 const char* data:: Set to NULL if not set or needed ("GET")

==== Return:

==== Example:
[source, c]
Serial.println("Sending GET request to REST server");
rest.request("/utc/now", "GET");

___
___
=== get
==== Function:
 Make a GET request to the remote server aka get the value of a resource from the REST server

==== Note:

==== Prototype:
[source, c]
 void get(const char* path, const char* data=NULL);

==== Parameters:
 const char* path:: Path that extends the URL of the REST request (command or data for the REST server)
 const char* data:: Pointer to data buffer

==== Defaults:
 const char* data:: Set to NULL if not set or needed ("GET")

==== Return:

==== Example:
[source, c]
Serial.println("Sending GET request to REST server");
rest.get("/utc/now");
char response[BUFLEN];
memset(response, 0, BUFLEN);
uint16_t code = rest.waitResponse(response, BUFLEN);
if(code == HTTP_STATUS_OK){
  Serial.print("Got the time: ");
  Serial.println(response);
} else {
  Serial.print("ARDUINO: GET failed: ");
  Serial.println(code);
}

___
___
=== post
==== Function:
 Make a POST request to the remote server with NULL-terminated data aka create a resource on the REST server

==== Note:

==== Prototype:
[source, c]
 void post(const char* path, const char* data);

==== Parameters:
 const char* path:: Path that extends the URL of the REST request (command or data for the REST server)
 const char* data:: Pointer to data buffer

==== Defaults:

==== Return:

==== Example:
[source, c]
Serial.println("Sending POST request to REST server");
rest.post("/customers","beegee-tokyo");

___
___
=== put
==== Function:
 Make a PUT request to the remote server with NULL-terminated data aka update a resource on the REST server

==== Note:

==== Prototype:
[source, c]
 void put(const char* path, const char* data);

==== Parameters:
 const char* path:: Path that extends the URL of the REST request (command or data for the REST server)
 const char* data:: Pointer to data buffer

==== Defaults:

==== Return:

==== Example:
[source, c]
Serial.println("Sending PUT request to REST server");
rest.put("/customers/beegee-tokyo","New customer name");

___
___
=== delete
==== Function:
 Make a DELETE request to the remote server with NULL-terminated data aka delete a resource on the REST server

==== Note:

==== Prototype:
[source, c]
 void put(const char* path, const char* data);

==== Parameters:
 const char* path:: Path that extends the URL of the REST request (command or data for the REST server)
 const char* data:: Pointer to data buffer

==== Defaults:

==== Return:

==== Example:
[source, c]
Serial.println("Sending DELETE request to REST server");
rest.del("/customers","beegee-tokyo");

___
___
=== getResponse
==== Function:
 Retrieve the response from the remote server, returns the HTTP status code, 0 if no response (may need to wait longer)

==== Note:
[WARNING]
Received packet is NOT null-terminated

==== Prototype:
[source, c++]
uint16_t getResponse(char* data, uint16_t maxLen);

==== Parameters:
 char* data:: Pointer to buffer for received packet
 uint16_t maxLen:: Size of buffer for received packet. If the received packet is larger than the buffer, the received packet will be truncated.

==== Defaults:

==== Return:
 uint16_t <len>:: Size of received data or 0 if no response

==== Example:
[source, c++]
#define BUFLEN 266
void loop()
{
  // process any callbacks coming from esp_link
  esp.Process();
  void loop()
  {
    // process any callbacks coming from esp_link
    esp.Process();
    // if we're connected make an HTTP request
    if(wifiConnected)
    {
      // Request /utc/now from the previously set-up server
      rest.get("/utc/now");
      char response[BUFLEN];
      memset(response, 0, BUFLEN);
      uint16_t code = rest.waitResponse(response, BUFLEN);
      if(code == HTTP_STATUS_OK)
      {
        Serial.println("ARDUINO: GET successful:");
        Serial.println(response);
      }
      else
      {
        Serial.print("ARDUINO: GET failed: ");
        Serial.println(code);
      }
      delay(1000);
    }
}

___
___
=== waitResponse
==== Function:
 Wait for the response from the remote server, returns the HTTP status code, 0 if no response (may need to wait longer)

==== Note:
[CAUTION]
**Blocks the Arduino code for 5 seconds! not recommended to use.**

//[TIP]
//Use callback function instead!

[WARNING]
Received packet is NOT null-terminated

==== Prototype:
 uint16_t waitResponse(char* data, uint16_t maxLen, uint32_t timeout=DEFAULT_REST_TIMEOUT);

==== Parameters:
 char* data:: Pointer to buffer for received packet
 uint16_t maxLen:: Size of buffer for received packet. If the received packet is larger than the buffer, the received packet will be truncated.
 uint32_t timeout:: Timout in milli seconds to wait for a response, defaults to 5000ms

==== Defaults:
uint32_t timeout:: Is the default timeout of 5 seconds if not set

==== Return:
 uint16_t <len>:: HTTP response from the REST server or 0 if no response

==== Example:
[source, c++]
#define BUFLEN 266
void loop() {
  // process any callbacks coming from esp_link
  esp.Process();
  // if we're connected make an HTTP request
  if(wifiConnected) {
    // Request /utc/now from the previously set-up server
    rest.get("/utc/now");
    char response[BUFLEN];
    memset(response, 0, BUFLEN);
    uint16_t code = rest.waitResponse(response, BUFLEN);
    if(code == HTTP_STATUS_OK){
      Serial.println("ARDUINO: GET successful:");
      Serial.println(response);
    } else {
      Serial.print("ARDUINO: GET failed: ");
      Serial.println(code);
    }
    delay(1000);
  }

___
___
